export { default as indexRouter } from './home'
export { default as customersRouter } from './customers'
export { default as managersRouter } from './managers'
export { default as booksRouter } from './books'
export { default as promotionsRouter } from './promotions'
export { default as transactionsRouter } from './transactions'
