export { default as index } from './home'
export { default as customers } from './customers'
export { default as managers } from './managers'
export { default as books } from './books'
export { default as promotions } from './promotions'
export { default as transactions } from './transactions'
