# Run this Dockerfile from the project's root folder using this command 
# docker build -t bookstore-mono-admin -f services/api/Dockerfile.ci .
# And then run it using this command
# docker run --name bookstore-mono-api --rm -d -p 8081:8081 bookstore-mono-api
FROM node:12-alpine
RUN mkdir -p /code/admin
WORKDIR /code/admin/
COPY ["package.json", "yarn.lock", "./"]
COPY ./scripts ./scripts
COPY ./node_modules ./node_modules
COPY ./services/shared ./services/shared
COPY ./services/admin ./services/admin
RUN yarn build:admin
EXPOSE 8082
CMD ["yarn", "start:admin:container"]